# Generated by Django 3.1.7 on 2021-03-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('sex', models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO'), ('O', 'OUTROS')], max_length=1)),
                ('language', models.CharField(choices=[('JS', 'JAVASCRIPT'), ('PY', 'PYTHON'), ('TY', 'TYPESCRIPT'), ('JV', 'JAVA'), ('C#', 'C#'), ('RB', 'BUBY')], max_length=2)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
